### PR TITLE
Add the ability to get at column data in custom components

### PR DESCRIPTION
**Pull request by JamesFreeman**
I'm creating a custom component that would allow uses to select the row via a checkbox, I can't do it via the htmlUnsafe as this feature was removed so I wanted to do it via a component, but I don't have access to the column data in the component.

Thoughts?

### CODE REVIEW

**Comment by AndreSouzaAbreu** [comment]
I didn't get exactly what you want to do. Do you want to provide a column which the users will be able to select one or

**Comment by JamesFreeman** [comment]
So I need to get at the data from the selected column, I can only get access to the the data set of the row at the moment. I want to be able to get at things like what field for that column I wanted to display etc.

I have a couple of use cases for this, one of my use case is I want to be able to create a custom component which will allow for a user to select a row via a checkbox, I can get access to the id that is in the row's data, but I can't get access to what field I'm trying to point at for that column.

Secondly, I want to be able to create a custom component, which will allow me to create a dynamic link bases on a bunch of parameters, i.e, CSS class selector, what the button should say etc. (I have this data on the column row now, I just can't access it).

If there is already a workout for this now, it'd be happy to implement that. 

Thanks for your time reviewing the PR so quickly, it's much appericated.

James.

**Comment by JamesFreeman** [comment]
I'm looking to try and do something like this: 

```vue
<template>
    <!-- Checkbox example -->
    <div>
        <input type="checkbox" :value="data[columns.field]" class="input" :name="`${column.field}[]`" id="">
    </div>
    
    <!-- Button Layout. -->
    <div>
        <a :href="`${columns.extraData.linkBase}/${data[columns.field]}`" :class="`btn ${columns.extraData.cssClass}`" v-text="columns.extraData.buttonText"></a>
    </div>
</template>

<script>
export default {
    props: {
        data: {
            type: Object,
            required: true,
        },
        columns: {
            type: Object,
            required: true,
        }
    }
}
</script>
```

**Comment by JamesFreeman** [comment]
I've made the change on my local machine, compiled it down, and this works without any BC.

This is my new component: 

```vue
<template>
    <div>
        {{data}}, {{column}}
    </div>
</template>

<script>
export default {
    props: {
        data: {
            type: Object,
            required: true,
        },
        column: {
            type: Object,
        }
    }
}
</script>
```

This is the output: 

Screenshot 2021-09-07 at 08 09 19

**Comment by AndreSouzaAbreu** [comment]
So, were you able to achieve what you wanted with this change?

If so, I'll merge the pull request because it allows for greater extensibility 

> I've made the change on my local machine, compiled it down, and this works without any BC.
> 
> This is my new component:
> 
> ```
> <template>
>     <div>
>         {{data}}, {{column}}
>     </div>
> </template>
> 
> <script>
> export default {
>     props: {
>         data: {
>             type: Object,
>             required: true,
>         },
>         column: {
>             type: Object,
>         }
>     }
> }
> </script>
> ```
> 
> This is the output:
> 
> Screenshot 2021-09-07 at 08 09 19

**Comment by JamesFreeman** [comment]
Yup, it worked nicely for me. When you merge it, when is the next release scheduled for? 

Thanks,
James.

**Comment by AndreSouzaAbreu** [comment]
I think till this weekend I can do it

**Comment by JamesFreeman** [comment]
Hey @AndreSouzaAbreu, sorry to be a pain, would you be able to sort out a release for this stuff today? I project that I'm working on needs this feature to be able to release. Is there anything I can do to help you with this?

**Comment by AndreSouzaAbreu** [comment]
@JamesFreeman done :D

**Pull request merged**
